### ISSUE TITLE
Error in rule multiQC

### ISSUE THREAD

**Issue by Ben7124** [tamirna/miND#1]
Hello,

I am trying to run the miND pipeline, but it stops around 80% of the way through. The specific error is "Error in rule MultiQC". I have pasted part of the MultiQC log below and the pipeline log below that. It looks like several modules in MultiQC are broken. Is there any way to skip the multiQC steps and continue with the rest of the pipeline? I really want to get the final plots and the differential expression analysis. Any help is much appreciated. Thank you.

[WARNING]         multiqc : MultiQC Version v1.12 now available!
[INFO   ]         multiqc : This is MultiQC v1.10.1
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/ubu/miND/output/small/fastqc_raw
[INFO   ]         multiqc : Searching   : /home/ubu/miND/output/small/fastqc_trimmed
[INFO   ]         multiqc : Searching   : /home/ubu/miND/output/small/logs/fastq_trimmed
Searching   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 60/60
[ERROR  ]         multiqc : Oops! The 'custom_content' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module custom_content raised an exception: Traceback (most recent call last):
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/multiqc.py"
, line 594, in run
    output = mod()
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/modules/cus
tom_content/custom_content.py", line 87, in custom_module_classes
    bm = BaseMultiqcModule()
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/modules/bas
e_module.py", line 45, in __init__
    config.update({anchor: mod_cust_config.get("custom_config", {})})
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/utils/confi
g.py", line 250, in update
    return update_dict(globals(), u)
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/utils/confi
g.py", line 256, in update_dict
    if isinstance(val, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
============================================================
[ERROR  ]         multiqc : Oops! The 'ngsderive' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module ngsderive raised an exception: Traceback (most recent call last):
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/multiqc.py"
, line 594, in run
    output = mod()
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/modules/ngs
derive/ngsderive.py", line 29, in __init__
    super(MultiqcModule, self).__init__(
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/modules/bas
e_module.py", line 45, in __init__
    config.update({anchor: mod_cust_config.get("custom_config", {})})
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/utils/confi
g.py", line 250, in update
    return update_dict(globals(), u)
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/utils/confi
g.py", line 256, in update_dict
    if isinstance(val, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
============================================================
[ERROR  ]         multiqc : Oops! The 'purple' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module purple raised an exception: Traceback (most recent call last):
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/multiqc.py"
, line 594, in run
    output = mod()
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/modules/pur
ple/purple.py", line 25, in __init__
    super(MultiqcModule, self).__init__(
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/modules/bas
e_module.py", line 45, in __init__
    config.update({anchor: mod_cust_config.get("custom_config", {})})
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/utils/confi
g.py", line 250, in update
    return update_dict(globals(), u)
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/utils/confi
g.py", line 256, in update_dict
    if isinstance(val, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
============================================================
[ERROR  ]         multiqc : Oops! The 'conpair' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module conpair raised an exception: Traceback (most recent call last):
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/multiqc.py"
, line 594, in run
    output = mod()
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/modules/con
pair/conpair.py", line 23, in __init__
    super(MultiqcModule, self).__init__(
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/modules/bas
e_module.py", line 45, in __init__
    config.update({anchor: mod_cust_config.get("custom_config", {})})
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/utils/confi
g.py", line 250, in update
    return update_dict(globals(), u)
  File "/home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23/lib/python3.10/site-packages/multiqc/utils/confi
g.py", line 256, in update_dict
    if isinstance(val, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'

*****PIPELINE LOG*******

Error in rule multiQC:
    jobid: 148
    output: output/small/multiqc/multiqc_report.html
    log: output/small/multiqc/multiqc.log (check log file(s) for error message)
    conda-env: /home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23
    shell:

        rm -fr 'output/small/multiqc/' && mkdir 'output/small/multiqc/'
        multiqc 'output/small/fastqc_raw/' 'output/small/fastqc_trimmed/' 'output/small/logs/fastq_trimmed/' --config multiqc_config.yaml -o 'output/small/multiqc/' > 'output/small/multiqc/multiqc.log' 2>&1

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Trying to restart job 148.

[Mon Jul  4 23:45:55 2022]
rule mappingBBDukSpikeInsCore:
    input: output/small/fastq_trimmed/DAY3_3_R1.fastq
    output: output/small/mapping_bbduk_spikeins_core/DAY3_3_R1.txt
    log: output/small/logs/mapping_bbduk_spikeins_core/DAY3_3_R1.log
    jobid: 74
    wildcards: filename=DAY3_3_R1
    threads: 6
    resources: tmpdir=/tmp

Activating conda environment: /home/ubu/miND/envs/tmp/b40f8b4d8f0e4656dc44f88f2fc830de
Removing temporary output file output/small/mapping_bbduk_spikeins_core/CONTROL_3_R1.txt.
[Mon Jul  4 23:45:57 2022]
Finished job 19.
137 of 174 steps (79%) done
Removing temporary output file output/small/mapping_bbduk_spikeins_core/DAY4_1_R1.txt.
[Mon Jul  4 23:45:57 2022]
Finished job 75.
138 of 174 steps (79%) done
Select jobs to execute...

[Mon Jul  4 23:45:57 2022]
rule multiQC:
    input: output/small/fastqc_trimmed/CONTROL_1_R1_fastqc.zip, output/small/fastqc_trimmed/CONTROL_2_R1_fastqc.zip, output/small/fastqc_trimmed/CONTROL_3_R1_fastqc.zip, output/small/fastqc_trimmed/DAY2_1_R1_fastqc.zip, output/small/fastqc_trimmed/DAY2_2_R1_fastqc.zip, output/small/fastqc_trimmed/DAY2_3_R1_fastqc.zip, output/small/fastqc_trimmed/DAY3_1_R1_fastqc.zip, output/small/fastqc_trimmed/DAY3_2_R1_fastqc.zip, output/small/fastqc_trimmed/DAY3_3_R1_fastqc.zip, output/small/fastqc_trimmed/DAY4_1_R1_fastqc.zip, output/small/fastqc_trimmed/DAY4_2_R1_fastqc.zip, output/small/fastqc_trimmed/DAY4_3_R1_fastqc.zip, output/small/fastqc_raw/CONTROL_1_R1_fastqc.zip, output/small/fastqc_raw/CONTROL_2_R1_fastqc.zip, output/small/fastqc_raw/CONTROL_3_R1_fastqc.zip, output/small/fastqc_raw/DAY2_1_R1_fastqc.zip, output/small/fastqc_raw/DAY2_2_R1_fastqc.zip, output/small/fastqc_raw/DAY2_3_R1_fastqc.zip, output/small/fastqc_raw/DAY3_1_R1_fastqc.zip, output/small/fastqc_raw/DAY3_2_R1_fastqc.zip, output/small/fastqc_raw/DAY3_3_R1_fastqc.zip, output/small/fastqc_raw/DAY4_1_R1_fastqc.zip, output/small/fastqc_raw/DAY4_2_R1_fastqc.zip, output/small/fastqc_raw/DAY4_3_R1_fastqc.zip, output/small/logs/fastq_trimmed/CONTROL_1_R1.log, output/small/logs/fastq_trimmed/CONTROL_2_R1.log, output/small/logs/fastq_trimmed/CONTROL_3_R1.log, output/small/logs/fastq_trimmed/DAY2_1_R1.log, output/small/logs/fastq_trimmed/DAY2_2_R1.log, output/small/logs/fastq_trimmed/DAY2_3_R1.log, output/small/logs/fastq_trimmed/DAY3_1_R1.log, output/small/logs/fastq_trimmed/DAY3_2_R1.log, output/small/logs/fastq_trimmed/DAY3_3_R1.log, output/small/logs/fastq_trimmed/DAY4_1_R1.log, output/small/logs/fastq_trimmed/DAY4_2_R1.log, output/small/logs/fastq_trimmed/DAY4_3_R1.log
    output: output/small/multiqc/multiqc_report.html
    log: output/small/multiqc/multiqc.log
    jobid: 148
    resources: tmpdir=/tmp

Select jobs to execute...
Activating conda environment: /home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23
[Mon Jul  4 23:46:00 2022]
Error in rule multiQC:
    jobid: 148
    output: output/small/multiqc/multiqc_report.html
    log: output/small/multiqc/multiqc.log (check log file(s) for error message)
    conda-env: /home/ubu/miND/envs/tmp/6a8daca3774047e70f8c2205e0113f23
    shell:

        rm -fr 'output/small/multiqc/' && mkdir 'output/small/multiqc/'
        multiqc 'output/small/fastqc_raw/' 'output/small/fastqc_trimmed/' 'output/small/logs/fastq_trimmed/' --config multiqc_config.yaml -o 'output/small/multiqc/' > 'output/small/multiqc/multiqc.log' 2>&1

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing temporary output file output/small/fastq_trimmed/DAY3_3_R1.fastq.
[Mon Jul  4 23:46:05 2022]
Finished job 74.
139 of 174 steps (80%) done
Removing temporary output file output/small/mapping_bowtie_spikeins/DAY3_2_R1.unmapped.fasta.
Removing temporary output file output/small/mapping_bowtie_genome/DAY3_2_R1.unmapped.fasta.
[Mon Jul  4 23:46:19 2022]
Finished job 61.
140 of 174 steps (80%) done
Removing temporary output file output/small/mapping_bowtie_spikeins/DAY3_1_R1.unmapped.fasta.
Removing temporary output file output/small/mapping_bowtie_genome/DAY3_1_R1.unmapped.fasta.
[Mon Jul  4 23:46:37 2022]
Finished job 53.
141 of 174 steps (81%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by andreasd** [comment]
Hi!

I'll take a closer look for the reason of this error later, but to answer your question if you could skip multiqc: yes, you can with two modifications in the Snakefile:

https://github.com/tamirna/miND/blob/efe8506cc521102489750b665d6003fe78debb43/Snakefile#L123

remove "{outPath}/multiqc/multiqc_report.html"

and 

https://github.com/tamirna/miND/blob/efe8506cc521102489750b665d6003fe78debb43/Snakefile#L150

remove the whole line ( inputList['multiQC'] = "%s/multiqc/multiqc_report.html" % outPath)

This should stop the pipeline from creating the multiQC file.

Let me know if this quick fix helped and i'll get back to this issue with a more permanent solution,

Andreas

**Comment by Ben7124** [comment]
Hi Andreas,

Thanks for your quick reply! I changed the snakemake lines and it gets past the multiQC steps, but it now gives me an error in the quantifySampleMappings step. I have 12 samples with 3 replicates per condition. It looks like there is an issue with an R command where it says the below. Do you have any idea what the issue could be? Thanks for your help again.

! Can't subset columns past the end.
ℹ Locations 4, 5, 6, and 7 don't exist.
ℹ There are only 3 columns.

I have pasted the partial log below.

Error in rule quantifySampleMappings:
    jobid: 99
    output: output/small/analysis_quantifySampleMappings/all_samples.csv, output/small/analysis_quantifySampleMappings/all_samples.dat, output/small/analysis_quantifySampleMappings/all_samples_perc.csv, output/small/analysis_quantifySampleMappings/all_samples_perc.dat, output/small/analysis_quantifySampleMappings/all_samples_genome_mapping.csv
    log: output/small/logs/analysis/quantifySampleMappings.log (check log file(s) for error message)
    conda-env: /home/ubu/miND/envs/tmp/736c7ddfa39a6aa0986849f99ddc5f3b
    shell:
        sleep 3 && Rscript scripts/quantifySampleMappings.R --outFile='output/small/analysis_quantifySampleMappings/all_samples.csv' --outFileGenomeMapping='output/small/analysis_quantifySampleMappings/all_samples_genome_mapping.csv' --sampleSheetFile='../exodata/Exosome_SampleContrastSheet_2.xls' --cores=6 output/small/mapping_bowtie_genome/CONTROL_1_R1.map output/small/mapping_bowtie_genome/CONTROL_2_R1.map output/small/mapping_bowtie_genome/CONTROL_3_R1.map output/small/mapping_bowtie_genome/DAY2_1_R1.map output/small/mapping_bowtie_genome/DAY2_2_R1.map output/small/mapping_bowtie_genome/DAY2_3_R1.map output/small/mapping_bowtie_genome/DAY3_1_R1.map output/small/mapping_bowtie_genome/DAY3_2_R1.map output/small/mapping_bowtie_genome/DAY3_3_R1.map output/small/mapping_bowtie_genome/DAY4_1_R1.map output/small/mapping_bowtie_genome/DAY4_2_R1.map output/small/mapping_bowtie_genome/DAY4_3_R1.map 2> output/small/logs/analysis/quantifySampleMappings.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Tue Jul  5 08:10:49 2022]
Error in rule combineAllMappingStats:
    jobid: 2
    output: output/small/analysis_sampleMappingStats/all_samples.csv, output/small/analysis_sampleMappingStats/all_samples_rpm_miRNA.csv, output/small/analysis_sampleMappingStats/all_samples_rpm_lib.csv, output/small/analysis_sampleMappingStats/all_samples_rpm_dist.dat
    log: output/small/logs/analysis/combineAllMappingStats.log (check log file(s) for error message)
    conda-env: /home/ubu/miND/envs/tmp/736c7ddfa39a6aa0986849f99ddc5f3b
    shell:
        sleep 3 && Rscript scripts/combineAllMappingStats.R --outFile='output/small/analysis_sampleMappingStats/all_samples.csv' --includeSequence=0  --sampleSheetFile='../exodata/Exosome_SampleContrastSheet_2.xls' output/small/analysis_sampleMappingStats/CONTROL_1_R1.csv output/small/analysis_sampleMappingStats/CONTROL_2_R1.csv output/small/analysis_sampleMappingStats/CONTROL_3_R1.csv output/small/analysis_sampleMappingStats/DAY2_1_R1.csv output/small/analysis_sampleMappingStats/DAY2_2_R1.csv output/small/analysis_sampleMappingStats/DAY2_3_R1.csv output/small/analysis_sampleMappingStats/DAY3_1_R1.csv output/small/analysis_sampleMappingStats/DAY3_2_R1.csv output/small/analysis_sampleMappingStats/DAY3_3_R1.csv output/small/analysis_sampleMappingStats/DAY4_1_R1.csv output/small/analysis_sampleMappingStats/DAY4_2_R1.csv output/small/analysis_sampleMappingStats/DAY4_3_R1.csv 2> output/small/logs/analysis/combineAllMappingStats.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Trying to restart job 2.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ubu/miND/.snakemake/log/2022-07-05T074745.240265.snakemake.log
(base) ubu@DESKTOP-9AKF01S:~/miND$ cd output/small/
(base) ubu@DESKTOP-9AKF01S:~/miND/output/small$ ls
analysis_sampleMappingStats  logs                 mapping_bowtie_genome  mapping_bowtie_rnacentral  mapping_mirdeep2_miRNA
fastq_trimmed                mapping_bowtie_cdna  mapping_bowtie_mirna   mapping_bowtie_spikeins
(base) ubu@DESKTOP-9AKF01S:~/miND/output/small$ cd logs/
(base) ubu@DESKTOP-9AKF01S:~/miND/output/small/logs$ cd analysis/
(base) ubu@DESKTOP-9AKF01S:~/miND/output/small/logs/analysis$ ls
combineAllMappingStats.log  quantifySampleMappings.log  sampleMappingStats
(base) ubu@DESKTOP-9AKF01S:~/miND/output/small/logs/analysis$ more quantifySampleMappings.log

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Attaching package: ‘magrittr’

The following object is masked from ‘package:tidyr’:

    extract

Loading required package: R.oo
Loading required package: R.methodsS3
R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.
R.oo v1.25.0 (2022-06-12 02:20:02 UTC) successfully loaded. See ?R.oo for help.

Attaching package: ‘R.oo’

The following object is masked from ‘package:R.methodsS3’:

    throw

The following object is masked from ‘package:magrittr’:

    equals

The following objects are masked from ‘package:methods’:

    getClasses, getMethods

The following objects are masked from ‘package:base’:

    attach, detach, load, save

R.utils v2.10.1 (2020-08-26 22:50:31 UTC) successfully loaded. See ?R.utils for help.

Attaching package: ‘R.utils’

The following object is masked from ‘package:magrittr’:

    extract

The following object is masked from ‘package:tidyr’:

    extract

The following object is masked from ‘package:utils’:

    timestamp

The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, inherits, isOpen, nullfile, parse,
    warnings

Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Error in `select()`:
! Can't subset columns past the end.
ℹ Locations 4, 5, 6, and 7 don't exist.
ℹ There are only 3 columns.
Backtrace:
     ▆
  1. ├─... %>% select(1:7)
  2. ├─dplyr::select(., 1:7)
  3. └─dplyr:::select.data.frame(., 1:7)
  4.   ├─dplyr:::tidyselect_fix_call(...)
  5.   │ └─base::withCallingHandlers(...)
  6.   └─tidyselect::eval_select(expr(c(...)), .data)
  7.     └─tidyselect:::eval_select_impl(...)
  8.       ├─tidyselect:::with_subscript_errors(...)
  9.       │ ├─base::tryCatch(...)
 10.       │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 11.       │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 12.       │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 13.       │ └─tidyselect:::with_entraced_errors(expr)
 14.       │   └─rlang::try_fetch(...)
 15.       │     └─base::withCallingHandlers(...)
 16.       └─tidyselect:::vars_select_eval(...)
 17.         └─tidyselect:::loc_validate(pos, vars, call = error_call)
 18.           └─vctrs::vec_as_location(pos, n = length(vars))
 19.             └─vctrs (local) `<fn>`()
 20.               └─vctrs:::stop_subscript_oob(...)
 21.                 └─vctrs:::stop_subscript(...)
 22.                   └─rlang::abort(...)
Execution halted

**Comment by andreasd** [comment]
would it be possible to share your sample contrast sheet (the xls file where you entered your samples and groups)?

this seems like there are columns in the second sheet missing (e.g. if you removed the comment box starting with "please note:").

thanks!

**Comment by Ben7124** [comment]
Here it is Andreas. In order for the program to read the file, I had to save it in "xls" format not in "xlsx". Thanks again for your help! I don't see the missing columns in the second sheet. Where should the "please note:" be?

[Test_SampleContrastSheet_2.xls](https://github.com/tamirna/miND/files/9055165/Test_SampleContrastSheet_2.xls)
!

**Comment by andreasd** [comment]
Dear Ben,

if you take a look at the template file (https://github.com/tamirna/miND/blob/main/SampleContrastSheet.example.xlsx) you see a box with tips about how to fill the columns. This box is missing in your file.

I have attached a sampleContrastSheet file with your data. Please try using this one. 

I also noticed that your file is in xls format (not like the template in xlsx). You can use LibreOffice (https://www.libreoffice.org/) to edit xlsx files should you have not access to excel.

Please try running the pipeline again with the contrast sheet attached and let me know if this helped.

Andreas

[Test_SampleContrastSheet_2.xlsx](https://github.com/tamirna/miND/files/9055518/Test_SampleContrastSheet_2.xlsx)

**Comment by Ben7124** [comment]
Hi Andreas, 

Thank you again for your help. I am running it now. The reason I save it as an xls is that the pipeline gives me the following errors when I save it as an xlsx. However, as an xls, the pipeline seems to be proceeding through the steps. 

AttributeError in line 15 of /home/ubu/miND/Snakefile:
'ElementTree' object has no attribute 'getiterator'
  File "/home/ubu/miND/Snakefile", line 15, in <module>
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 296, in wrapper
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 867, in __init__
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_xlrd.py", line 22, in __init__
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 353, in __init__
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_xlrd.py", line 37, in load_workbook
  File "/root/miniconda3/lib/python3.9/site-packages/xlrd/__init__.py", line 130, in open_workbook
  File "/root/miniconda3/lib/python3.9/site-packages/xlrd/xlsx.py", line 812, in open_workbook_2007_xml
  File "/root/miniconda3/lib/python3.9/site-packages/xlrd/xlsx.py", line 266, in process_stream
Running pipeline
Config file config.yaml is extended by additional config specified via the command line.
AttributeError in line 15 of /home/ubu/miND/Snakefile:
'ElementTree' object has no attribute 'getiterator'
  File "/home/ubu/miND/Snakefile", line 15, in <module>
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 296, in wrapper
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 867, in __init__
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_xlrd.py", line 22, in __init__
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 353, in __init__
  File "/root/miniconda3/lib/python3.9/site-packages/pandas/io/excel/_xlrd.py", line 37, in load_workbook
  File "/root/miniconda3/lib/python3.9/site-packages/xlrd/__init__.py", line 130, in open_workbook
  File "/root/miniconda3/lib/python3.9/site-packages/xlrd/xlsx.py", line 812, in open_workbook_2007_xml
  File "/root/miniconda3/lib/python3.9/site-packages/xlrd/xlsx.py", line 266, in process_stream

**Comment by Ben7124** [comment]
Hi Andreas, 
Sorry to bother you again, but the pipeline completes 99% of the way and then I get an "xfun" version error when it is about to generate the report. Below is the error I get:

Activating conda environment: /home/ubu/miND/envs/tmp/736c7ddfa39a6aa0986849f99ddc5f3b
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  namespace ‘xfun’ 0.22 is being loaded, but >= 0.27 is required
Calls: :: ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
[Thu Jul  7 10:15:45 2022]
Error in rule makeHTMLReport:
    jobid: 1
    output: output/Testmod_2/analysis/report.html
    log: output/Testmod_2/logs/analysis/report.log (check log file(s) for error message)
    conda-env: /home/ubu/miND/envs/tmp/736c7ddfa39a6aa0986849f99ddc5f3b

RuleException:
CalledProcessError in line 163 of /home/ubu/miND/Snakefile:
Command 'source /root/miniconda3/bin/activate '/home/ubu/miND/envs/tmp/736c7ddfa39a6aa0986849f99ddc5f3b'; set -euo pipefail;  Rscript --vanilla -e 'rmarkdown::render("/home/ubu/miND/.snakemake/scripts/tmp4b1dlvms.report.Rmd", output_file="/home/ubu/miND/output/Testmod_2/analysis/report.html", quiet=TRUE, knit_root_dir = "/home/ubu/miND", params = list(rmd="/home/ubu/miND/.snakemake/scripts/tmp4b1dlvms.report.Rmd"))'' returned non-zero exit status 1.
  File "/home/ubu/miND/Snakefile", line 163, in __rule_makeHTMLReport
  File "/root/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Trying to restart job 1.
Select jobs to execute...

[Thu Jul  7 10:15:45 2022]
rule makeHTMLReport:
    input: ../exodata/Testmod_SampleContrastSheet_2.xls, output/Testmod_2/analysis_sampleMappingStats/all_samples.csv, output/Testmod_2/analysis_sampleMappingStats/all_samples_rpm_miRNA.csv, output/Testmod_2/analysis_quantifySampleMappings/all_samples.csv, output/Testmod_2/analysis_quantifySampleMappings/all_samples_genome_mapping.csv, output/Testmod_2/analysis_differentialExpression
    output: output/Testmod_2/analysis/report.html
    log: output/Testmod_2/logs/analysis/report.log
    jobid: 1
    resources: tmpdir=/tmp

Activating conda environment: /home/ubu/miND/envs/tmp/736c7ddfa39a6aa0986849f99ddc5f3b
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  namespace ‘xfun’ 0.22 is being loaded, but >= 0.27 is required
Calls: :: ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
[Thu Jul  7 10:15:45 2022]
Error in rule makeHTMLReport:
    jobid: 1
    output: output/Testmod_2/analysis/report.html
    log: output/Testmod_2/logs/analysis/report.log (check log file(s) for error message)
    conda-env: /home/ubu/miND/envs/tmp/736c7ddfa39a6aa0986849f99ddc5f3b

RuleException:
CalledProcessError in line 163 of /home/ubu/miND/Snakefile:
Command 'source /root/miniconda3/bin/activate '/home/ubu/miND/envs/tmp/736c7ddfa39a6aa0986849f99ddc5f3b'; set -euo pipefail;  Rscript --vanilla -e 'rmarkdown::render("/home/ubu/miND/.snakemake/scripts/tmpew8xvrb8.report.Rmd", output_file="/home/ubu/miND/output/Testmod_2/analysis/report.html", quiet=TRUE, knit_root_dir = "/home/ubu/miND", params = list(rmd="/home/ubu/miND/.snakemake/scripts/tmpew8xvrb8.report.Rmd"))'' returned non-zero exit status 1.
  File "/home/ubu/miND/Snakefile", line 163, in __rule_makeHTMLReport
  File "/root/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ubu/miND/.snakemake/log/2022-07-07T095255.839778.snakemake.log

**Comment by Ben7124** [comment]
Hi Andreas,
The issue was fixed by changing the R env file replacing Xfun 0.22 with 0.31. Thanks for all your help. I am able to get the report and plots. I don't know why the xlsx format doesn't work but the xls does. I will close this issue for now.

**Comment by andreasd** [comment]
Dear Ben,

thanks for the update. We had have previously issues with this package and it seems that also your issues with fastqc/mutliqc is a problem with the conda environments. I'll take a closer look on how to optimize them and check if I can reproduce it here. 

Thanks for your help reporting and also finding these issues! If you have any further comments/suggestions or questions, please feel free to reach out!

Andreas

**Comment by zbaida-achraf** [comment]
I have the same error in rule combineAllMappingStats

rule combineAllMappingStats:
input: output/Test-1/analysis_sampleMappingStats/ENDO_ST_Z072001_CL_P_Z072001SV1_F_S85_R1_001.csv, output/Test-1/analysis_sampleMappingStats/ENDO_ST_Z072003_BA_A_Z072003SV1_F_S86_R1_001.csv, output/Test-1/$
output: output/Test-1/analysis_sampleMappingStats/all_samples.csv, output/Test-1/analysis_sampleMappingStats/all_samples_rpm_miRNA.csv, output/Test-1/analysis_sampleMappingStats/all_samples_rpm_lib.csv, ou$
log: output/Test-1/logs/analysis/combineAllMappingStats.log
jobid: 2
reason: Missing output files: output/Test-1/analysis_sampleMappingStats/all_samples.csv, output/Test-1/analysis_sampleMappingStats/all_samples_rpm_miRNA.csv; Input files updated by another job: output/Test$
resources: tmpdir=/tmp

Activating conda environment: envs/tmp/f9f219586f630daa622e0131ffaa6c08_
[Wed Dec 28 10:10:14 2022]
Error in rule combineAllMappingStats:
jobid: 2
input: output/Test-1/analysis_sampleMappingStats/ENDO_ST_Z072001_CL_P_Z072001SV1_F_S85_R1_001.csv, output/Test-1/analysis_sampleMappingStats/ENDO_ST_Z072003_BA_A_Z072003SV1_F_S86_R1_001.csv, output/Test-1/$
output: output/Test-1/analysis_sampleMappingStats/all_samples.csv, output/Test-1/analysis_sampleMappingStats/all_samples_rpm_miRNA.csv, output/Test-1/analysis_sampleMappingStats/all_samples_rpm_lib.csv, ou$
log: output/Test-1/logs/analysis/combineAllMappingStats.log (check log file(s) for error details)
conda-env: /data/diana/miND_Pipe/miND/envs/tmp/f9f219586f630daa622e0131ffaa6c08_
shell:
sleep 3 && Rscript scripts/combineAllMappingStats.R --outFile='output/Test-1/analysis_sampleMappingStats/all_samples.csv' --includeSequence=0 --sampleSheetFile='../data/lot7/Test-1_SampleContrastSheet$
(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

How did you resolve it ?
