### ISSUE TITLE
Error in rule makeHTMLReport and combineAllMappingStats

### ISSUE THREAD

**Issue by zbaida-achraf** [tamirna/miND#2]
Hello,

I am trying to run the miND pipeline, when i choose just one sample this is the error that i have in rule makeHTMLReport

Error in rule makeHTMLReport:
    jobid: 1
    input: ../data/lot7/SampleContrastSheet_1samples.xlsx, output/SampleContrastSheet_1samples/analysis_sampleMappingStats/all_samples.csv, output/SampleContrastSheet_1samples/analysis_sampleMappingStats/all_samples_rpm_miRNA.csv, output/SampleContrastSheet_1samples/analysis_quantifySampleMappings/all_samples.csv, output/SampleContrastSheet_1samples/analysis_quantifySampleMappings/all_samples_genome_mapping.csv
    output: output/SampleContrastSheet_1samples/analysis/report.html
    log: output/SampleContrastSheet_1samples/logs/analysis/report.log (check log file(s) for error details)
    conda-env: /data/diana/miND_Pipe/miND/envs/tmp/d4d71ba8d15b68b3f47efdeb72ddc658_

RuleException:
CalledProcessError in file /data/diana/miND_Pipe/miND/Snakefile, line 167:
Command 'source /data/diana/miND_Pipe/miniconda3/envs/mind-workflow-env/bin/activate '/data/diana/miND_Pipe/miND/envs/tmp/d4d71ba8d15b68b3f47efdeb72ddc658_'; set -euo pipefail;  Rscript --vanilla -e 'rmarkdown::render("/data/diana/miND_Pipe/miND/.snakemake/scripts/tmppjf50tfw.report.Rmd", output_file="/data/diana/miND_Pipe/miND/output/SampleContrastSheet_1samples/analysis/report.html", quiet=TRUE, knit_root_dir = "/data/diana/miND_Pipe/miND", params = list(rmd="/data/diana/miND_Pipe/miND/.snakemake/scripts/tmppjf50tfw.report.Rmd"))'' returned non-zero exit status 1.
  File "/data/diana/miND_Pipe/miND/Snakefile", line 167, in __rule_makeHTMLReport
  File "/data/diana/miND_Pipe/miniconda3/envs/mind-workflow-env/lib/python3.9/concurrent/futures/thread.py", line 58, in run

And when i use 4 samplesID i have an error in combineAllMappingStats:

Error in rule combineAllMappingStats:
    jobid: 2
    input: output/SampleContrastSheet_4samples/analysis_sampleMappingStats/ENDO_ST_Z072001_CL_P_Z072001SV1_F_S85_R1_001.csv, output/SampleContrastSheet_4samples/analysis_sampleMappingStats/ENDO_ST_Z072003_BA_A_Z072003SV1_F_S86_R1_001.csv, output/SampleContrastSheet_4samples/analysis_sampleMappingStats/ENDO_ST_Z072009_ME_M_Z072009SV1_F_S92_R1_001.csv, output/SampleContrastSheet_4samples/analysis_sampleMappingStats/ENDO_ST_Z072011_NI_L_Z072011SV1_F_S94_R1_001.csv, ../data/lot7/SampleContrastSheet_4samples.xlsx
    output: output/SampleContrastSheet_4samples/analysis_sampleMappingStats/all_samples.csv, output/SampleContrastSheet_4samples/analysis_sampleMappingStats/all_samples_rpm_miRNA.csv, output/SampleContrastSheet_4samples/analysis_sampleMappingStats/all_samples_rpm_lib.csv, output/SampleContrastSheet_4samples/analysis_sampleMappingStats/all_samples_rpm_dist.dat
    log: output/SampleContrastSheet_4samples/logs/analysis/combineAllMappingStats.log (check log file(s) for error details)
    conda-env: /data/diana/miND_Pipe/miND/envs/tmp/d4d71ba8d15b68b3f47efdeb72ddc658_
    shell:
        sleep 3 && Rscript scripts/combineAllMappingStats.R --outFile='output/SampleContrastSheet_4samples/analysis_sampleMappingStats/all_samples.csv' --includeSequence=0  --sampleSheetFile='../data/lot7/SampleContrastSheet_4samples.xlsx' output/SampleContrastSheet_4samples/analysis_sampleMappingStats/ENDO_ST_Z072001_CL_P_Z072001SV1_F_S85_R1_001.csv output/SampleContrastSheet_4samples/analysis_sampleMappingStats/ENDO_ST_Z072003_BA_A_Z072003SV1_F_S86_R1_001.csv output/SampleContrastSheet_4samples/analysis_sampleMappingStats/ENDO_ST_Z072009_ME_M_Z072009SV1_F_S92_R1_001.csv output/SampleContrastSheet_4samples/analysis_sampleMappingStats/ENDO_ST_Z072011_NI_L_Z072011SV1_F_S94_R1_001.csv 2> output/SampleContrastSheet_4samples/logs/analysis/combineAllMappingStats.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Can you please help me to resolve it.

**Comment by andreasd** [comment]
sorry, for the late reply. the error here is that the pipeline expects more than one sample in the contrast sheet and it seems like you only had one in there. i'll check if we can adapt the pipeline to also process single samples, but most of the reporting the pipeline does relies on multiple samples, so the report won't be very informative.
